pinder/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "profiles#index"

  resources :profiles do
    resources :likes
  end

end

pinder/app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :profile

end

pinder/app/models/profile.rb
class Profile < ActiveRecord::Base

  has_attached_file :owner_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :owner_image, content_type: /\Aimage\/.*\z/
  validates :owner_name, length: { minimum: 1 }, presence: true
  validates_numericality_of :owner_age, is_greater_than: 18
  validates :owner_likes, length: { minimum: 1 }, presence: true
  validates :owner_dislikes, length: { minimum: 1 }, presence: true

  has_attached_file :pet_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pet_image, content_type: /\Aimage\/.*\z/
  validates :pet_name, length: { minimum: 1 }, presence: true
  validates_numericality_of :pet_age, is_greater_than: 1
  validates :pet_likes, length: { minimum: 1 }, presence: true
  validates :pet_dislikes, length: { minimum: 1 }, presence: true

  belongs_to :user
  has_many :likes

end

pinder/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

     def self.from_omniauth(auth)
       where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
         user.email = auth.info.email
         user.password = Devise.friendly_token[0,20]
       end
     end
end

pinder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pinder/app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    @profiles = Profile.all.to_a
  end

  def new
    @profile = Profile.find(params[:profile_id])
    @like = @profile.likes.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @profile.likes.create
    redirect_to profile_likes_path
  end

end

pinder/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    if !session[:profile_index]
      session[:profile_index] = 0
    end
    @profiles = Profile.all.to_a
  end

  def new
    @profile = Profile.new
  end

  def create
    @user = current_user
    @profile = Profile.create(profile_params)
    if @profile.save
      @user.update({ :profile_id => @profile.id })
      @profile.update({ :user_id => @user.id })
      redirect_to '/profiles'
    else
      render 'new'
    end
  end

  def show
    @profile = Profile.find(params[:id])
    @profiles = Profile.all.to_a
  end

  def update
    session[:profile_index] += 1
    redirect_to '/'
  end

  private

  def profile_params
    params.require(:profile).permit(:owner_name, :owner_age, :gender, :sexual_preference, :owner_likes, :owner_dislikes, :pet_name, :pet_age, :pet_species, :pet_likes, :pet_dislikes, :owner_image, :pet_image)
  end

end

pinder/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

pinder/app/helpers/application_helper.rb
module ApplicationHelper
end

pinder/app/helpers/likes_helper.rb
module LikesHelper
end

pinder/app/helpers/owner_likes_helper.rb
module OwnerLikesHelper
end

pinder/app/helpers/play_helper.rb
module PlayHelper
end

pinder/app/helpers/profiles_helper.rb
module ProfilesHelper
end

pinder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body><div id="sign_in">
  <%= image_tag "pinder.png", :class => "main_logo" %><br><br>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <span class="links"><%= link_to "Sign up", new_user_registration_path %></span>
    <span class="links"><%= link_to "Sign in", new_user_session_path %></span>
    <br><br>
    <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <br><br>
  <% end %>
  <%= yield %>
    </div>
  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
</body>
</html>

pinder/app/views/likes/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id="main">
      <section class="more">
        <%= button_to "Like to see more?", profiles_path, method: :get, :class => "button_more" %>
      </section>
    <section class="owner">
    <%= image_tag @profiles[session[:profile_index]].owner_image.url(:medium) %><br><br>
  </section>
  <section class="middle">
    <b>Owner Name: </b><%= @profiles[session[:profile_index]].owner_name %><br><br>
    <b>Owner Age: </b><%= @profiles[session[:profile_index]].owner_age %><br><br>
    <b>Gender: </b><%= @profiles[session[:profile_index]].gender %><br><br>
    <b>Sexual Preference: </b><%= @profiles[session[:profile_index]].sexual_preference %><br><br>
    <b>Owner Likes: </b><%= @profiles[session[:profile_index]].owner_likes %><br><br>
    <b>Owner Dislikes: </b><%= @profiles[session[:profile_index]].owner_dislikes %><br><br>

    <b>Pet Name: </b><%= @profiles[session[:profile_index]].pet_name %><br><br>
    <b>Pet Age: </b><%= @profiles[session[:profile_index]].pet_age %><br><br>
    <b>Species: </b><%= @profiles[session[:profile_index]].pet_species %><br><br>
    <b>Pet Likes: </b><%= @profiles[session[:profile_index]].pet_likes %><br><br>
    <b>Pet Dislikes: </b><%= @profiles[session[:profile_index]].pet_dislikes %><br>
  </section>
  <section class="pet">
    <%= image_tag @profiles[session[:profile_index]].pet_image.url(:medium) %>
  </section>
  </div>
  </body>
</html>

pinder/app/views/likes/new.html.erb
<%= form_for [@profile, @like] do |f| %>
  <%= f.label "Are you sure you want to like this person?" %>
  <%= f.submit "Like!" %>
<% end %>

pinder/app/views/profiles/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id="main">
    <% if user_signed_in? %>
    <% if current_user.profile_id == nil %>
    You don't yet have a profile
    <br><br>
    <%= link_to "Create Profile", new_profile_path %><br>
    <% else %>
    <section class="like">
      <%= button_to "WOOF WOOF",  profile_path(@profiles), method: :get, :class => "button_like" %>
    </section>
    <section class="details">
    <b>Name:</b> <%= @profiles[session[:profile_index]].pet_name %>
    <b>Age:</b> <%= @profiles[session[:profile_index]].pet_age %><br><br>
    <%= image_tag @profiles[session[:profile_index]].pet_image.url(:medium) %>
  </section>
  <section class="dislike">
    <%= button_to "DOWN BOY", profile_path(@profiles), method: :put, :class => "button_dislike" %>
  </section>
    <% end %>
    <% else %>
    Please sign up or sign in to use Pinder
    <% end %>
    </div>
  </body>
</html>

pinder/app/views/profiles/new.html.erb
<% if @profile.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved: </h2>
    <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<div id='main'>
<div id='owner'>
<%= form_for @profile do |f| %>
  <%= f.label :owner_name %>:
  <%= f.text_field :owner_name %><br><br>
  <%= f.label :owner_age %>:
  <%= f.text_field :owner_age %><br><br>
  <%= f.label :gender %>:
  <%= f.select :gender, ["Male", "Female", "Other"] %><br><br>
  <%= f.label :sexual_preference %>
  <%= f.select :sexual_preference, ["Straight", "Homosexual", "Bisexual", "Other"] %><br><br>
  <%= f.label :owner_likes %>:
  <%= f.text_field :owner_likes %><br><br>
  <%= f.label :owner_dislikes %>:
  <%= f.text_field :owner_dislikes %><br><br>
  <%= f.label :owner_image %>
  <%= f.file_field :owner_image %><br><br>
  <%= f.label :pet_name %>:
  <%= f.text_field :pet_name %><br><br>
  <%= f.label :pet_age %>:
  <%= f.text_field :pet_age %><br><br>
  <%= f.label :pet_species %>:
  <%= f.select :pet_species, ["Dog", "Cat", "Fish", "Reptile", "Rodent", "Other"] %><br><br>
  <%= f.label :pet_likes %>:
  <%= f.text_field :pet_likes %><br><br>
  <%= f.label :pet_dislikes %>:
  <%= f.text_field :pet_dislikes %><br><br>
  <%= f.label :pet_image %>
  <%= f.file_field :pet_image %><br><br>
</div>
<div id='submit'>
  <%= f.submit "Submit Profile" %>
</div>
</div>
<% end %>

pinder/app/views/profiles/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id="main">
    <section class="like">
      <%= button_to "HUBBA HUBBA", profile_likes_path(@profiles), method: :post, :class => "button_like" %>
    </section>
    <section class="details">
    <b>Name:</b> <%= @profiles[session[:profile_index]].owner_name %>
    <b>Age:</b> <%= @profiles[session[:profile_index]].owner_age %><br><br>
    <%= image_tag @profiles[session[:profile_index]].owner_image.url(:medium) %><br><br>
  </section>
  <section class="dislike">
    <%= button_to "No thanks", profile_path(@profiles), method: :put, :class => "button_dislike" %>
  </section>
</div>

  </body>
</html>